### PR TITLE
First page

### PR DESCRIPTION
**Pull request by pykennedy**
Buttons on toolbar light up as intended. Will make a new branch for getting the windows to pop-up once this gets merged.

### CODE REVIEW

**Comment by BryceBrown** [comment]
There looks like alot of repeated code in setLights. Try to come up with a cleaner way of implementing this.

**Comment by pykennedy** [comment]
i tried to when i first implemented it, but the best way i could come up
with was to set titles or tags to numbers, and then just do something like
Integer.parseInt(view.getTag()) but that also seemed kind of gross

**Comment by pykennedy** [comment]
its also not repeated, each one is slightly different, so every time i
tried to convert this into some sort of loop i ran into the issue of
detecting which light to turn on and off, and to keep this in a loop i
would need a bunch of if statements and it would basically turn into the
same thing i have now

**Comment by BryceBrown** [comment]
Try making a method that sets all of the icons to dark, then depending on
what item is passed in (via title) set that icons image to the light one
(again, also respecting the on/off flag). I would actually think about
storing the on/off boolean in the tag of the menu item, as it will make the
code cleaner and you will have a few less class variables to worry about
(as a side note you may have to use the Boolean object instead of boolean
for this).

**Pull request closed without merging**
