### PR TITLE
First page

### PR DESCRIPTION
**Pull request by pykennedy**
fixed the static variable reference

### CODE REVIEW

**Comment by pykennedy** [comment]
im having trouble styling the addPOI window. I want it to look like this
picture but i can't get things to lock down in the appropriate place, and i
doubt hard coding height dp's until i get the perfect ratio is a good
strategy. I also want an "enter" button on both the title and notes
<EditText> to be hidden (shown by the faint dotted box in my picture), but
show up when the user is typing in one of those fields. The biggest
difficulty right now is getting my dropdown menu to scale and be stylable.

Lastly, im not sure how to go about setting the text on my custom popups.
I've gotten it to load my custom view so it has some placeholder buttons,
but the title is blank. I know i can't store poi information yet but i want
to at least figure out the code to changing the marker's title so it will
showup in the popup window.

I have pushed my code so u can see it.

**Comment by BryceBrown** [comment]
I would say keep playing around with the layouts to get the styling right. If linear isn;t working, try relative layout.

We can talk about the intended edit text enter functionality on sunday.

for setting the title, when you load up the view, simply do a view.findViewById on the root view in the infowindowadapter to get a reference to the textView, then set it;s text from there.

**Comment by pykennedy** [comment]
i got the view to look correct. Now my issue is trying to implement button
functionality. I'm just trying to test right now how to println the text
from the POI title the user enters. However, in my fragment
PoiDetailWIndow.java its onClick() method never gets called. I've set a
breakpoint in its first line and it never gets called. I can't find
solutions on google. It seems like it should work since this is how i've
done every other onClick() that wasn't inline.

**Comment by pykennedy** [comment]
also i've pushed my code so u can see where im at

**Comment by pykennedy** [comment]
i've also tried messing around with various onCreate()'s and even doing
setOnClickListener(this) which is what i thought i was missing isn't
working. I'm assuming im just screwing up some android hierarchy where my
fragment doesn't respond to on clicks due to how it was created?

**Comment by BryceBrown** [comment]
Interesting, it looks like google maps Info Windows are rendered too images, and can only have onclick listeners for the whole window:

http://stackoverflow.com/a/20283674

So, another option would be to, when a marker is selected, to have a toolbar on the top display the title and actions. Otherwise, we'll have to think about  another option.

**Comment by pykennedy** [comment]
I knew info windows can't actually have buttons that act like buttons and
would have to do some form of detecting location of the click yourself to
fiddle with the buttons. However im just trying to get my buttons on the
addPOI fragment to work (the sliding window).

For our sake we'll just call the sliding fragments the "sliders" since
using "window" for both is confusing us.

So the buttons on my slider aren't registering any sort of onClick(). The
button animates like it's being clicked, but onClick() never gets called.

**Pull request merged**
